language:
  python

os:
  - linux

python:
  - '3.4'
  - '3.5'
  - '3.6'

git:
  depth: false

install:
  pip install -r test_requirements.txt

script:
  coverage run -m unittest discover -s test
