# TravisCI YAML Config
# Describes the unit test execution

language:
  python

os:
  - linux
# Uncomment to enable Mac OSX builds.
#  - osx

# Add entries for all python versions to test.
python:
  - '3.5'
  - '3.6'

# Uncomment to disable shallow clone, allowing your TravisCI job to checkout other refs.
git:
  depth: false

install:
  pip install -r test_requirements.txt

script:
  coverage run -m unittest discover -s test
